USER ITEMS

In [2]:
# se importan las librerias que se van a usar 
import gzip
import ast
import chardet
import pandas as pd
import nltk

Primero se procede a abrir el archivo user_items

In [3]:
def descomprimir_file_items(ruta, variable_anidada):
    # Detección automática del encoding
    with open(ruta, 'rb') as archivo_binario:
        resultado = chardet.detect(archivo_binario.read())
        encoding_detectado = resultado['encoding']

    # Lectura del archivo utilizando el encoding detectado
    fila = []
    with gzip.open(ruta, 'rt', encoding=encoding_detectado) as archivo:
        for line in archivo.readlines():
            fila.append(ast.literal_eval(line))

    # Creación del DataFrame y procesamiento adicional
    df = pd.DataFrame(fila)
    df = df.explode(variable_anidada).reset_index(drop=True)

    if not df.empty:
        df = pd.concat([df, pd.json_normalize(df[variable_anidada])], axis=1)
        df = df.drop(columns=variable_anidada)

    return df

def descomprimir_file_items(ruta, variable_anidada):
    '''Esta función recibe una ruta de acceso a un archivo json anidado y carga la información en un
    DataFrame'''
    fila = []
    with gzip.open(ruta, 'rt', encoding='MacRoman') as archivo:
        for line in archivo.readlines():
            fila.append(ast.literal_eval(line))

    df = pd.DataFrame(fila)
    df = df.explode(variable_anidada).reset_index(drop=True)
    
    if not df.empty:
        df = pd.concat([df, pd.json_normalize(df[variable_anidada])], axis=1)
        df = df.drop(columns=variable_anidada)

    return df

In [4]:
file_path_items = "../datasets/users_items.json.gz"

In [5]:
user_items = descomprimir_file_items(file_path_items,'items')

Se revisa como esta compuesto el df

In [6]:
user_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5170015 entries, 0 to 5170014
Data columns (total 8 columns):
 #   Column            Dtype
---  ------            -----
 0   user_id           object
 1   items_count       int64
 2   steam_id          object
 3   user_url          object
 4   item_id           object
 5   item_name         object
 6   playtime_forever  float64
 7   playtime_2weeks   float64
dtypes: float64(2), int64(1), object(5)
memory usage: 315.6+ MB

In [7]:
user_items

,user_id,items_count,steam_id,user_url,item_id,item_name,playtime_forever,playtime_2weeks
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,10,Counter-Strike,6.0,0.0
1,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,20,Team Fortress Classic,0.0,0.0
2,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,30,Day of Defeat,7.0,0.0
3,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,40,Deathmatch Classic,0.0,0.0
4,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,50,Half-Life: Opposing Force,0.0,0.0
...,...,...,...,...,...,...,...,...
5170010,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,373330,All Is Dust,0.0,0.0
5170011,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,388490,One Way To Die: Steam Edition,3.0,3.0
5170012,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,521570,You Have 10 Seconds 2,4.0,4.0
5170013,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,519140,Minds Eyes,3.0,3.0
5170014,edward_tremethick,0,76561198331598578,http://steamcommunity.com/id/edward_tremethick,NaN,NaN,NaN,NaN

In [10]:
user_items.isna().sum()

user_id             0
items_count         0
steam_id            0
user_url            0
item_id             0
item_name           0
playtime_forever    0
playtime_2weeks     0
dtype: int64

In [ ]:
user_items[(user_items["item_id"].isna()) & (user_items["item_name"].isna()) & (user_items["playtime_forever"].isna()) & (user_items["playtime_2weeks"].isna())]

,user_id,items_count,steam_id,user_url,item_id,item_name,playtime_forever,playtime_2weeks
3733,Wackky,0,76561198039117046,http://steamcommunity.com/id/Wackky,NaN,NaN,NaN,NaN
3849,76561198079601835,0,76561198079601835,http://steamcommunity.com/profiles/76561198079...,NaN,NaN,NaN,NaN
6019,hellom8o,0,76561198117222320,http://steamcommunity.com/id/hellom8o,NaN,NaN,NaN,NaN
6523,starkillershadow553,0,76561198059648579,http://steamcommunity.com/id/starkillershadow553,NaN,NaN,NaN,NaN
7237,darkenkane,0,76561198058876001,http://steamcommunity.com/id/darkenkane,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
5169470,76561198316380182,0,76561198316380182,http://steamcommunity.com/profiles/76561198316...,NaN,NaN,NaN,NaN
5169471,76561198316970597,0,76561198316970597,http://steamcommunity.com/profiles/76561198316...,NaN,NaN,NaN,NaN
5169472,76561198318100691,0,76561198318100691,http://steamcommunity.com/profiles/76561198318...,NaN,NaN,NaN,NaN
5170006,XxLaughingJackClown77xX,0,76561198328759259,http://steamcommunity.com/id/XxLaughingJackClo...,NaN,NaN,NaN,NaN
5170014,edward_tremethick,0,76561198331598578,http://steamcommunity.com/id/edward_tremethick,NaN,NaN,NaN,NaN

se evidencias que las filas nulas son las mismas en las 4 columnas, por ellos se proceden a eliminar ya que no aportaran al analisis

In [9]:
user_items.dropna(inplace=True)

Se eliminan las filas que no se consideran utiles para el analisis

In [ ]:
user_items.drop(columns=['user_url','playtime_2weeks','steam_id'])

,user_id,items_count,item_id,item_name,playtime_forever
0,76561197970982479,277,10,Counter-Strike,6.0
1,76561197970982479,277,20,Team Fortress Classic,0.0
2,76561197970982479,277,30,Day of Defeat,7.0
3,76561197970982479,277,40,Deathmatch Classic,0.0
4,76561197970982479,277,50,Half-Life: Opposing Force,0.0
...,...,...,...,...,...
5170009,76561198329548331,7,346330,BrainBread 2,0.0
5170010,76561198329548331,7,373330,All Is Dust,0.0
5170011,76561198329548331,7,388490,One Way To Die: Steam Edition,3.0
5170012,76561198329548331,7,521570,You Have 10 Seconds 2,4.0
5170013,76561198329548331,7,519140,Minds Eyes,3.0

Para finalizar se cargara la informacion a un csv y se comprimira ya que github solo permite archivos de hasta 100mb

In [ ]:
user_items.to_csv('../datasets/user_items.csv',index=False)

In [ ]:
with gzip.open('../datasets/user_items.csv.gz', 'wb') as f:
    user_items.to_csv(f, index=False, encoding='utf-8')